[profile]
name = "blargg"
description = "Blargg test suite with full state and pixel output."
trigger = "tcycle"

[fields]
cpu = "registers"
ppu = ["registers", "output"]
timer = true
interrupt = true
serial = true
