[profile]
name = "gbmicrotest"
description = "Full dump for gbmicrotest cycle-accuracy tests."
trigger = "tcycle"

[fields]
cpu = "registers"
ppu = "all"
timer = true
interrupt = true
serial = true

[fields.memory]
test_result = "FF80"
test_expect = "FF81"
test_pass   = "FF82"
